variables:
  URL_DEPLOY_SH: "https://gitlab.ebi.ac.uk/api/v4/projects/3377/repository/files/helm-deploy.sh/raw?ref=master&private_token=${GITLAB_USER_API_TOKEN}"
  INTEGRATION_TESTS_TRIGGER: "https://gitlab.ebi.ac.uk/api/v4/projects/4778/trigger/pipeline"
stages:
  - test
  - build
  - build_docker_image
  - deploy

.mvn:
  image: maven:3.8.2-openjdk-17-slim
  before_script:
    - java --version
    - mvn --version

test:
  extends: .mvn
  stage: test
  script:
    - mkdir -p /data
    - mvn clean verify
    - curl -X POST --fail -F token=${INTEGRATION_TESTS_TRIGGER_TOKEN} -F ref=${CI_COMMIT_REF_NAME} ${INTEGRATION_TESTS_TRIGGER}

build:
  only:
    refs:
      - main
      - dev
  extends: .mvn
  stage: build
  script:
    - mvn -DskipTests clean package
    - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
  artifacts:
    expire_in: 2 days
    paths:
      - target/dependency

build_docker_image:
  only:
    refs:
      - main
      - dev
  stage: build_docker_image
  image: docker:latest
  tags:
    - dind
  services:
    - docker:dind
  script:
    - docker --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - CONTAINER_IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - echo "image name will be ${CONTAINER_IMAGE}"
    - docker build -t ${CONTAINER_IMAGE} --no-cache -f deploy/Dockerfile .
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"

.kubectl:
  image: dockerhub.ebi.ac.uk/uniprot/deployment/containers/helm
  before_script:
    - wget -O deploy.sh "${URL_DEPLOY_SH}"
    - echo "--no-cache --no-cookies was not used by wget"
    - if [ ! -f deploy.sh ]; then echo "k8s deployment script is missing"; exit 1; fi
    - chmod +x deploy.sh

dev-deploy:
  only:
    refs:
      - dev
  stage: deploy
  extends: .kubectl
  script:
    - ./deploy.sh ENV=DV APP_NAME=protvar-be K8S_NAMESPACE=protvar-dev imageTag="${CI_COMMIT_SHORT_SHA}"

prod-deploy:
  only:
    refs:
      - main
  stage: deploy
  extends: .kubectl
  script:
    - ./deploy.sh ENV=FB APP_NAME=protvar-be K8S_NAMESPACE=protvar imageTag="${CI_COMMIT_SHORT_SHA}"
    - ./deploy.sh ENV=PD APP_NAME=protvar-be K8S_NAMESPACE=protvar imageTag="${CI_COMMIT_SHORT_SHA}"