apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  serviceName: rabbit-service
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - image: rabbitmq:3.12.10-management-alpine
          name: rabbit
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
            memory: 200Mi
          limits:
            memory: 200Mi
            storage: 5Gi
        storageClassName: standard-nfs-production